In [2]:
# Step 1 : Import the required libraries 

import pandas as pd 

# Step 2: Load the url

url = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population"

# Step 3: Read the HTML Tables from the URL

tables = pd.read_html(url, storage_options={"User-Agent": "Mozilla/5.0 (learning-project)"})

# Step 4: Check the number of tables found

print(f"Number of tables found: {len(tables)}")

# Step 5: Display the first table
tables[0].head()

Number of tables found: 3

,Location,Population,% of world,Date,Source (official or from the United Nations),Notes
0,World,8.232000e+09,100%,13 Jun 2025,UN projection[1][3],NaN
1,India,1.429404e+09,17.3%,1 Jul 2026,Official projection[4],[b]
2,China,1.404890e+09,17.0%,31 Dec 2025,Official estimate[5],[c]
3,United States,3.417849e+08,4.1%,1 Jul 2025,Official estimate[6],[d]
4,Indonesia,2.883151e+08,3.5%,31 Dec 2025,National annual projection[7],NaN

In [4]:
import pandas as pd

url1 = "https://en.wikipedia.org/wiki/Computer_science"


tables = pd.read_html(url1, storage_options={"User-Agent": "Mozilla/5.0 (learning-project)"    })


print(f"Number of tables found: {len(tables)}")

tables[3].head()

Number of tables found: 18

,0,1,2,3,4
0,NaN,NaN,NaN,NaN,NaN
1,Coding theory,Channel capacity,Algorithmic information theory,Signal detection theory,Kolmogorov complexity

In [8]:
import tkinter as tk

window = tk.Tk()
window.title("Wikipedia Table Viewer")
window.geometry("300x200")

def on_click():
    label.config(text="Button Clicked!")

label = tk.Label(window, text="Click the button to see the message.")
label.pack(pady=10)

entry = tk.Entry(window)
entry.pack(pady=10)

button = tk.Button(window, text="Click Me", command=on_click)
button.pack(pady=10)

window.mainloop()